"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const userAuth_1 = require("../config/middlewares/userAuth");
const validate_1 = require("../config/middlewares/validate");
const controllers_1 = require("./controllers.");
const botApp = express_1.default.Router();
botApp.post("/delete-payment/:id", userAuth_1.authenticate, controllers_1.deletePayment);
botApp.post("/", userAuth_1.authenticate, controllers_1.getBots);
botApp.post("/refs", userAuth_1.authenticate, controllers_1.getRefs);
botApp.post("/buy", userAuth_1.authenticate, (0, validate_1.validateBuyBot)(), controllers_1.buyBot);
botApp.post("/payments", userAuth_1.authenticate, controllers_1.getPayments);
botApp.post("/investments", userAuth_1.authenticate, controllers_1.getInvestments);
botApp.post("/invest", userAuth_1.authenticate, (0, validate_1.validateInvest)(), controllers_1.invest);
botApp.post("/add-payment", userAuth_1.authenticate, (0, validate_1.validateStartPayment)(), controllers_1.paymentHandler);
botApp.post("/add-payment/:id", userAuth_1.authenticate, controllers_1.updatePayment);
exports.default = botApp;
